# -*- coding: utf-8 -*-
"""4110E113_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XcZq2f2BHh5RX1pGQNawkwAaZbqEYA8H
"""

a = input('Enter your name:')
print('HEllo ,'+ a)

x = (input("請輸入："))
x

b = x+50
b

x = int (input("請輸入："))
x

b =(x+50)
b

a = '''iashuhuhqbwbdsuhfuia
auqahfoancaos
aiwdishibguefuckauwdsbbuheua.'''
print(a)

x = 1.10
y = 1
z = -35.59

print(type(x))
print(type(y))
print(type(z))

x = ["apple", "banana", "cherry", "apple", "cherry"]
print(x)

dict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 2022
}
print(dict)

list = ["apple"]
print(list[:5])

list = ["apple", "banana", "cherry"]
print(list[0])

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))

x = 35e3
y = 12E4

print(type(x))
print(type(y))

x = 3+5j
print(type(x))

x = 1    
y = 2.8  
z = 1j   
#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)

#convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

b = "Hello, World!"
print(b[2:])

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "c" in x:
    newlist.append(x)

print(newlist)

fruits = ["kiwi", "banana", "cherry", "apple", "water"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

stduent = {
  "ID": "4110E113",
  "name": "wea",
  "born": 2022
}
stduent["number"] = 2
print(stduent)

myfamily = {
  "me" : {
    "name" : "ran",
    "year" : 2003
  },
  "bro" : {
    "name" : "Tobi",
    "year" : 2001
  },
  "sis" : {
    "name" : "Emy",
    "year" : 1998
  }
}
for x, y in myfamily.items():
  print(x, y)

x = 6
y = 2

print(x % y)

x = 1
y = 2

print(x % y)

x = 4125152
y = 2

print(x % y)

x = 2
y = 5

print(x ** y)

x = 2
y = 10

print(x ** y)

x = 4125252
y = 2

print(x // y)

x = 4125251
y = 2

print(x // y)

x = 5

x += 3

print(x)

x = 20

x += 3

print(x)

x = 

x &= 3

print(x)

x = 5
y = 8

print(x != y)

x = 8

print(x > 6 and x < 9)

x = 8
y = 7

print(x / y)

x = ["0", "21"]
y = ["0", "21"]
z = x

print(x is z)
#UNDERSANAD!
print(x is y)

print(x == y)

x = 3

print(not(x > 3 and x < 10))

x = 5
y = 3
# (! is not)
print(x != y)

x = ["1", "0"]

print("1" not in x)

x = "hey, 4110E113!"
print(x[:8])

a = "hello, 4110e113!"
print(a.upper())

x ="HELLO, 4110E113"
print(lower())

x ="HELLO, 4110E113"
print(x.lower())

a = "Hello, 3000E113!"
print(a.replace("300", "411"))

a = "hey"
b = "4110E113"
c = a + "\t" + b
print(c)

height = 100
x = "my height is {}"
print(x.format(height))

txt = "i'm good\t maybe\nnice to meet u"
print(txt)

x = "hElLo, HeLlO"
x.capitalize()

x = "Hello, 4110E113"
y = "l"
x.count(y)

x = ["a", "b", "c"]
x[0:2] = "x", "y"
print(x)

x = [1, 2, 3]
x.insert(0,0)
print(x)

x = ["1", "2", "3"]
del x[0]
print(x)

txt = ["0", "1", "2"]
for x in txt:
  print(x)

num1 = ["0422530", "12346271", "2456", "3345783", "4230462"]
num2 = []

for x in num1:
  if "0" in x:
    num2.append(x)

print(num2)

num = [0, 1, 2, 3, 4]
num.sort()
print(num)

num1 = ["0", "1", "2"]
num2 = num1.copy()
print(num2)

num1 = [4, 1, 1]
num2 = [0, "E", 1, 1, 3]

num1.extend(num2)
print(num1)

num = ['0', '1', '2']
num.append("3")
print(num)

student = {
  "ID": "4110E113",
  "name": "wea",
}
x = student["ID"]
print(x)

student = {
  "ID": "4110E113",
  "name": "wea",
}
student["name"] = "wearan"
print(student)

student = {
  "ID": "4110E113",
  "name": "yuki",
  "year": 1964
}
del student["year"]
print(student)

student = {
  "ID": "4110E113",
  "name": "yuki",
}
for x, y in student.items():
  print(x, y)

student = {
  "ID": "4110E113",
  "name": "yuki",
}
txt = student.copy()

for x, y in txt.items():
  print(x, y)

car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.keys()

car["color"] = "white"

print(x)

myfamily = {
  "me" : {
    "name" : "ran",
    "year" : 2003
  },
  "bro" : {
    "name" : "Tobi",
    "year" : 2001
  },
  "sis" : {
    "name" : "Emy",
    "year" : 1998
  }
}

myfamily.clear()
print(myfamily)

print(10 & 5)

