# -*- coding: utf-8 -*-
"""4110E113_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XcZq2f2BHh5RX1pGQNawkwAaZbqEYA8H
"""

a = input('Enter your name:')
print('HEllo ,'+ a)

x = int(input("請輸入："))
x

b = x+50
b

